package computer_lab_inventory;

import java.awt.*;
import java.awt.event.*;
import java.util.Scanner;
import java.sql.*;

public class add_dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(add_dashboard.class.getName());

    /**
     * Creates new form add_dashboard
     */
    Scanner sc = new Scanner(System.in);
String url = "jdbc:mysql://localhost:3306/lab_asset_management";
String user = "root";
String pass = "";
String sql_equipment = "INSERT INTO equipment (equipment_name, category, brand, model, purchase_date) VALUES (?, ?, ?, ?, ?)";
String sql_status =
"INSERT INTO status (equipment_id, location, condition_state) VALUES (?, ?, ?)";
    public add_dashboard() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        brand_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        model_field = new javax.swing.JTextField();
        purchase_date_field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        location_field = new javax.swing.JTextField();
        condition_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        category_field = new javax.swing.JComboBox<>();
        add_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 200));

        jLabel1.setText("Name: ");

        name_field.addActionListener(this::name_fieldActionPerformed);

        jLabel2.setText("Category:");

        jLabel3.setText("Brand:");

        brand_field.addActionListener(this::brand_fieldActionPerformed);

        jLabel4.setText("Model:");

        model_field.addActionListener(this::model_fieldActionPerformed);

        purchase_date_field.addActionListener(this::purchase_date_fieldActionPerformed);

        jLabel5.setText("Purchase Date:");

        jLabel6.setText("Location:");

        location_field.addActionListener(this::location_fieldActionPerformed);

        condition_field.addActionListener(this::condition_fieldActionPerformed);

        jLabel7.setText("Condition:");

        category_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Input Devices", "Output Devices", "Storage Devices", "Processing Devices", "Communication Devices", "Other Devices/Items" }));
        category_field.addActionListener(this::category_fieldActionPerformed);

        add_button.setText("Add");
        add_button.addActionListener(this::add_buttonActionPerformed);

        exit_button.setText("Exit");
        exit_button.addActionListener(this::exit_buttonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(category_field, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brand_field, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(model_field, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purchase_date_field, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(location_field, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(condition_field, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_button)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exit_button))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(exit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(category_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brand_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(model_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchase_date_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(location_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(condition_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(add_button)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_fieldActionPerformed

    private void brand_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brand_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brand_fieldActionPerformed

    private void model_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_model_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_model_fieldActionPerformed

    private void purchase_date_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchase_date_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchase_date_fieldActionPerformed

    private void location_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_location_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_location_fieldActionPerformed

    private void condition_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_condition_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_condition_fieldActionPerformed

    private void category_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_category_fieldActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here:
    String equipment_name = name_field.getText();
    String category = (String) category_field.getSelectedItem();
    String brand = brand_field.getText();
    String model = model_field.getText();
    String purchase_date = purchase_date_field.getText();
    String location = location_field.getText();
    String condition = condition_field.getText();

    try (Connection connection =
            DriverManager.getConnection(url, user, pass)) {

        // IMPORTANT: enable transaction control
        connection.setAutoCommit(false);

        // INSERT EQUIPMENT (return generated ID)
        PreparedStatement statement_equipment =
                connection.prepareStatement(
                        sql_equipment,
                        Statement.RETURN_GENERATED_KEYS);

        statement_equipment.setString(1, equipment_name);
        statement_equipment.setString(2, category);
        statement_equipment.setString(3, brand);
        statement_equipment.setString(4, model);
        statement_equipment.setString(5, purchase_date);

        int equipmentInserted = statement_equipment.executeUpdate();

        if (equipmentInserted > 0) {

            // GET AUTO GENERATED equipment_id
            ResultSet rs = statement_equipment.getGeneratedKeys();

            if (rs.next()) {

                int equipment_id = rs.getInt(1);

                // INSERT STATUS
                PreparedStatement statement_status =
                        connection.prepareStatement(sql_status);

                statement_status.setInt(1, equipment_id);
                statement_status.setString(2, location);
                statement_status.setString(3, condition);

                 
                statement_status.executeUpdate();
            }
        }

        connection.commit();
        System.out.println("Equipment added successfully!");

    } catch (Exception e) {
        e.printStackTrace();
    }

    dispose();
    }//GEN-LAST:event_add_buttonActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        // TODO add your handling code here:
       dispose();
    }//GEN-LAST:event_exit_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new add_dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JTextField brand_field;
    private javax.swing.JComboBox<String> category_field;
    private javax.swing.JTextField condition_field;
    private javax.swing.JButton exit_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField location_field;
    private javax.swing.JTextField model_field;
    private javax.swing.JTextField name_field;
    private javax.swing.JTextField purchase_date_field;
    // End of variables declaration//GEN-END:variables
}
