/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package computer_lab_inventory;
import java.awt.Toolkit;
import javax.swing.*;
import java.awt.event.*;
import javax.swing.table.*;
import java.sql.*;
import java.util.Scanner;
import javax.swing.DefaultListModel;

public class dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboard.class.getName());

    /**
     * Creates new form dashboard
     */
         
Scanner sc = new Scanner(System.in);
String url = "jdbc:mysql://localhost:3306/lab_asset_management";
String user = "root";
String pass = "";
String sql = "INSERT INTO equipment (equipment_name, category, brand, model, purchase_date) VALUES (?, ?, ?, ?, ?)";

    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        add_updates_button = new javax.swing.JButton();
        maintenance_button = new javax.swing.JButton();
        report_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        dashboard = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        search_bar = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        search_bar_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        all_assets = new javax.swing.JTable();
        refresh_button = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        add_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_updates_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_updates_button.setText("ADD/UPDATES");
        add_updates_button.addActionListener(this::add_updates_buttonActionPerformed);
        jPanel1.add(add_updates_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 190, 70));

        maintenance_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        maintenance_button.setText("MAINTENANCE");
        maintenance_button.addActionListener(this::maintenance_buttonActionPerformed);
        jPanel1.add(maintenance_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 190, 70));

        report_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        report_button.setText("REPORT");
        report_button.addActionListener(this::report_buttonActionPerformed);
        jPanel1.add(report_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 190, 70));

        exit_button.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        exit_button.setText("EXIT");
        jPanel1.add(exit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, 110, 43));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 720));

        dashboard.setBackground(new java.awt.Color(153, 153, 255));
        dashboard.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search_bar.addActionListener(this::search_barActionPerformed);
        jPanel2.add(search_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Input Devices", "Output Devices", "Storage Devices", "Processing Devices", "Communication Devices", "Other Devices/Items" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 170, 30));

        search_bar_button.setText("Search");
        search_bar_button.addActionListener(this::search_bar_buttonActionPerformed);
        jPanel2.add(search_bar_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 90, 30));

        all_assets.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        all_assets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Equipment", "Name", "Brand", "Model", "Purchase Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        all_assets.setRowHeight(30);
        jScrollPane1.setViewportView(all_assets);
        if (all_assets.getColumnModel().getColumnCount() > 0) {
            all_assets.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 760, 530));

        refresh_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        refresh_button.setText("Refresh");
        refresh_button.addActionListener(this::refresh_buttonActionPerformed);
        jPanel2.add(refresh_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 630, 80, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Status");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, 100, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 640, 100, 40));

        add_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add_button.setText("Add");
        add_button.addActionListener(this::add_buttonActionPerformed);
        jPanel2.add(add_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, 100, 40));

        update_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        update_button.setText("Update");
        update_button.addActionListener(this::update_buttonActionPerformed);
        jPanel2.add(update_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 100, 40));

        dashboard.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Maintenance Log");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 50));

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("+Add New Mentenance");
        jButton5.addActionListener(this::jButton5ActionPerformed);
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 200, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "EquipmentID", "Name", "Issue Description", "Date Reported", "Date_Repaired", "Remarks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 760, 570));

        dashboard.addTab("tab2", jPanel3);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        dashboard.addTab("tab3", jPanel4);

        getContentPane().add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 870, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_updates_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_updates_buttonActionPerformed
        // TODO add your handling code here:
        dashboard.setSelectedIndex(0);
    }//GEN-LAST:event_add_updates_buttonActionPerformed

    private void maintenance_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenance_buttonActionPerformed
        // TODO add your handling code here:
        dashboard.setSelectedIndex(1);
    }//GEN-LAST:event_maintenance_buttonActionPerformed

    private void report_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_buttonActionPerformed
        // TODO add your handling code here:
        dashboard.setSelectedIndex(2);
    }//GEN-LAST:event_report_buttonActionPerformed

    private void search_barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_barActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_barActionPerformed

    private void search_bar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_bar_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_bar_buttonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void refresh_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_buttonActionPerformed
        // TODO add your handling code here:
        try {
            Connection connection = DriverManager.getConnection(url, user, pass);
            PreparedStatement statement = connection.prepareStatement(sql);
            DefaultTableModel model = (DefaultTableModel) all_assets.getModel();

            // clear existing rows
            model.setRowCount(0);

            String selectSQL = "SELECT * FROM equipment";

            PreparedStatement selectStatement = connection.prepareStatement(selectSQL);
            ResultSet rs = selectStatement.executeQuery();

            while(rs.next()) {
                int id = rs.getInt("equipment_id");
                String equipment_name = rs.getString("equipment_name");
                String category = rs.getString("category");
                String brand = rs.getString("brand");
                String equipment_model = rs.getString("model");
                String purchase_date = rs.getString("purchase_date");

                model.addRow(new Object[]{
                    "#"+id,
                    equipment_name,
                    category,
                    brand ,
                    equipment_model,
                    purchase_date
                });
            }
        }  catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_refresh_buttonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        status_dashboard status = new status_dashboard();
        status.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here:
        add_dashboard add = new add_dashboard();
        add.setVisible(true);
    }//GEN-LAST:event_add_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        // TODO add your handling code here:
        update_dashboard update = new update_dashboard();
        update.setVisible(true);
    }//GEN-LAST:event_update_buttonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        AddMentenanceDialog popup = new AddMentenanceDialog(this,true);
        popup.setLocationRelativeTo(this);
        popup.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JButton add_updates_button;
    private javax.swing.JTable all_assets;
    private javax.swing.JTabbedPane dashboard;
    private javax.swing.JButton exit_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton maintenance_button;
    private javax.swing.JButton refresh_button;
    private javax.swing.JButton report_button;
    private javax.swing.JTextField search_bar;
    private javax.swing.JButton search_bar_button;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
