/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package computer_lab_inventory;

import java.awt.*;
import java.awt.event.*;
import java.util.Scanner;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Gildork
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form login
     */
        Scanner sc = new Scanner(System.in);
String url = "jdbc:mysql://localhost:3306/lab_asset_management";
            String user = "root";
            String pass = "";

    




    
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        username_field = new javax.swing.JTextField();
        login_button = new javax.swing.JButton();
        password_field = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username_field.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel2.add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 87, 280, 70));

        login_button.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        login_button.setText("LOGIN");
        login_button.addActionListener(this::login_buttonActionPerformed);
        jPanel2.add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 350, 280, 75));

        password_field.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel2.add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 219, 280, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Password");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Username");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 56, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 380, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 1090, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        // TODO add your handling code here:
    String username = username_field.getText();
    String password = password_field.getText();
    
    try{
        String sql_login = "SELECT * FROM user WHERE username=? AND password=?";
        Connection conn = DriverManager.getConnection(url, user, pass);
        PreparedStatement pst = conn.prepareStatement(sql_login);
        
        pst.setString(1, username);
        pst.setString(2, password);
        
        ResultSet rs= pst.executeQuery();
       
        if(rs.next()){
            JOptionPane.showMessageDialog(this,"login");
            
    dashboard dash= new dashboard();
    dash.setVisible(true);
    
    dispose();
        }else{
           JOptionPane.showMessageDialog(this,"wrong");  
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    
    }//GEN-LAST:event_login_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JTextField username_field;
    // End of variables declaration//GEN-END:variables
}
